services:
  rewritten:
    image: rewritten
    ports:
      - "5001:5001"
    volumes:
      - ./videos:/app/static/videos
      - ./database:/app/rewritten/database
    env_file:
      - .env

  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ./traefik:/etc/traefik:ro
      - ./letsencrypt:/letsencrypt
