"""Add student and assignment relationships with explicit FK names

Revision ID: 89826fb69246
Revises: 9081c1e6e095
Create Date: 2025-03-30 09:09:21.752117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89826fb69246'
down_revision = '9081c1e6e095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_sessions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sessions_assignment_id', 'assignments', ['assignment_id'], ['id'])
        batch_op.create_foreign_key('fk_sessions_student_id', 'students', ['student_id'], ['id'])

    with op.batch_alter_table('student_assignment_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_session_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_progress_session_id', 'sessions', ['current_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_assignment_progress', schema=None) as batch_op:
        batch_op.drop_constraint('fk_progress_session_id', type_='foreignkey')
        batch_op.drop_column('current_session_id')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_student_id', type_='foreignkey')
        batch_op.drop_constraint('fk_sessions_assignment_id', type_='foreignkey')
        batch_op.drop_column('assignment_id')
        batch_op.drop_column('student_id')

    op.create_table('_alembic_tmp_sessions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('scenario', sa.VARCHAR(length=100), nullable=False),
    sa.Column('current_scene_id', sa.INTEGER(), nullable=True),
    sa.Column('partial_narrative', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('assignment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='fk_sessions_assignment_id'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_sessions_student_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
