"""empty message

Revision ID: 9081c1e6e095
Revises: 
Create Date: 2025-03-29 21:44:10.082975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9081c1e6e095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scene_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('scenario',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_scenario_partial_narrative', ['scenario', 'partial_narrative'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.alter_column('scenario',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_column('media_urls')
        batch_op.drop_column('narrative_data')
        batch_op.drop_column('decision_history')
        batch_op.drop_column('scene_prompts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scene_prompts', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('decision_history', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('narrative_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('media_urls', sa.TEXT(), nullable=True))
        batch_op.alter_column('scenario',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('scene_cache', schema=None) as batch_op:
        batch_op.drop_constraint('uq_scenario_partial_narrative', type_='unique')
        batch_op.alter_column('scenario',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
