"""Add auth0_id to Teacher and Student models

Revision ID: c57f42971670
Revises: 
Create Date: 2025-03-29 21:20:48.726188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57f42971670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_videos', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['auth0_id'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['auth0_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth0_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth0_id')

    with op.batch_alter_table('class_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
